env:
  env_name: "simple_cluster"
  env_kwargs:
    N: 4
    shuffle: true
    local_ratio: 0.9

eval_env:
  env_name: "simple_cluster"
  env_kwargs:
    N: 4
    shuffle: true
    local_ratio: 0.9

eval_cb_kwargs:
  deterministic: true
  eval_freq: 10000
  n_eval_episodes: 100
  render: false

policy_kwargs:
  feature_extractor_name: "Selector"
  feature_extractor_kwargs:
    n_select: 3
    has_target_pos: false

algo: "ppo"

num_timesteps: 6_000_000
