env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 5
    local_ratio: 0
    shuffle: true
    reward_only_single_agent: true

eval_env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 5
    local_ratio: 0
    shuffle: true

eval_cb_kwargs:
  deterministic: true
  eval_freq: 10000
  n_eval_episodes: 100
  render: false

policy_kwargs:
  feature_extractor_name: "AttnSelectorPolicy"
  feature_extractor_kwargs:
    n_select: 3

algo: "ppo"

num_timesteps: 6_000_000
