env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 3
    local_ratio: 0.1
    shuffle: true
    reward_agent_for_closest_landmark: true

eval_env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 3
    local_ratio: 0.1
    shuffle: true
    reward_agent_for_closest_landmark: true

eval_cb_kwargs:
  deterministic: true
  eval_freq: 10000
  n_eval_episodes: 100
  render: false

policy_kwargs:
  feature_extractor_name: "CrossAttentionSimpleSpread"
  feature_extractor_kwargs:
    embedding_size: 16

algo: "ppo"

num_timesteps: 6_000_000