env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 3
    local_ratio: 0
    shuffle: true

eval_env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 3
    local_ratio: 0
    shuffle: true

eval_cb_kwargs:
  deterministic: true
  eval_freq: 10000
  n_eval_episodes: 100
  render: false

policy_kwargs:
  feature_extractor_name: "CustomAttentionMeanEmbeddingsExtractorSimpleSpread"
  feature_extractor_kwargs:
    embedding_size: 16
    keys: ["my_vel", "my_pos", "other_pos", "entity_pos"]

algo: "ppo"

num_timesteps: 6_000_000
