env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 4
    local_ratio: 0
    shuffle: true

eval_env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 4
    local_ratio: 0
    shuffle: true

eval_cb_kwargs:
  deterministic: true
  eval_freq: 100000
  n_eval_episodes: 100
  render: false

policy_kwargs:
  net_arch: []
  feature_extractor_name: "MeanEmbeddingExtractor"
  feature_extractor_kwargs:

algo_kwargs:
  ent_coef: 0.01
  n_steps: 10000

algo: "ppo"

num_timesteps: 25_000_000
checkpoint_path: experimenter-results/me-ent-coeff_6/final_model.zip
