env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 4
    local_ratio: 0
    shuffle: true

eval_env:
  env_name: "custom_simple_spread"
  env_kwargs:
    N: 4
    local_ratio: 0
    shuffle: true

eval_cb_kwargs:
  deterministic: true
  eval_freq: 10000
  n_eval_episodes: 100
  render: false

policy_kwargs:
  feature_extractor_name: "Selector"
  feature_extractor_kwargs:
    n_select: 3

algo: "ppo"

num_timesteps: 6_000_000
checkpoint_path: experimenter-results/selector_1/eval/best_model.zip
train_only_feature_extractor: true
